### ISSUE TITLE
blender 4.1

### ISSUE THREAD

**Issue by acyc070** [hypov8/blender_kingpin_models#5]
error when exporting ANY model in 4.1.
i tried to export cube model:
======================
Kingpin Model Exporter.
Version: (1.2.6)
=======================
Getting Skins            :   0.00%
Getting Skins:            100% Done. (0.00 sec)
Count:  0
Width:  256
Height: 256
===============
Getting mesh data        :   0.00%
Caught error exporting model
=======================

**Comment by samyj-lucsyj-programist** [comment]
IDK

**Comment by acyc070** [comment]
https://developer.blender.org/docs/release_notes/4.1/ i hope this will help

**Comment by acyc070** [comment]
Python: Traceback (most recent call last):
  File "C:\Users\z\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\NEWKINGPIN\export_kp.py", line 924, in Export_MD2_fn
    setup_data_fn(self, context)
  File "C:\Users\z\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\NEWKINGPIN\export_kp.py", line 698, in setup_data_fn
    setupInternalArrays_fn(self)  # generate mesh/objects
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\z\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\NEWKINGPIN\export_kp.py", line 60, in setupInternalArrays_fn
    getMeshArrays_fn(
  File "C:\Users\z\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\NEWKINGPIN\common_kp.py", line 774, in getMeshArrays_fn
    fillMeshArrays(me, faceuv, None, uv_layer, custom_vn))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\z\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\NEWKINGPIN\common_kp.py", line 680, in fillMeshArrays
    me.calc_normals_split()
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Mesh' object has no attribute 'calc_normals_split'

**Comment by hypov8** [comment]
thanks for the details
`calc_normals_split` has been removed in 4.1. replaced with `corner_normals`
its still beta, so trying to work out alternative code.
it dont help i am still on win7. will update it soon

**Comment by hypov8** [comment]
added 4.1 updated https://github.com/hypov8/blender_kingpin_models/commit/e84092243a9ae80ef042efb63210afd12a7a0cf2
https://github.com/hypov8/blender_kingpin_models/releases

**Comment by samyj-lucsyj-programist** [comment]
thanks
